Blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Blog_Module import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('Blog_Module.urls')),
    url(r'',include('comments.urls')),
]

Blog_Module/urls.py
from django.conf.urls import url,include
from Blog_Module import views
from Blog import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

path_end = r'(?P<path>[\w\d_ -/.]*)$'
app_name = 'Blog'
urlpatterns = [
    url(r'^$',views.blog_index.as_view()),
    url(r'^article/(?P<pk>[0-9]+)/?$',views.blog_detail,name='detail'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]{1,2})/?$', views.archives),
    url(r'^category/(?P<pk>[0-9]+)/?$', views.category),
    url(r'^tag/(?P<tag_name>.+)/?$', views.tag),
    url(r'^search/?$', views.search,name='search'),
    url(r'^love/?$', views.Love,name='Love'),
    url(r'^resume/?$', views.Resume,name='Resume'),
    #url(r'^sendmail/(?P<emailto>[\w.%+-]+@[A-Za-z0-9.-]+[A-Za-z]{2,4})/', views.sendMail,name='SendMail'),
    url(r'^contact/?$', views.contact,name='Contact'),
    url(r'^about/?$',views.aboutMe,name='AboutMe'),
    url(r'upload/?$',views.Upload,name="Upload"),
    url(r'get_data/?$',views.get_data,name='get_data'),
    url(r'^check_is_login$', views.check_is_login, name='check_is_login'),
    url(r'^user_logout$', views.user_logout, name='user_logout'),
    url(r'^user_login$', views.user_login, name='user_login'),
    url(r'^user_reg$',views.user_reg,name='user_reg'),
    url(r'^user_active/([a-zA-Z]+)$',views.user_active,name='user_active'),
    url(r'^accounts/login/$',auth_views.login,name='login'),
    url(r'^modify_avatar/?$',views.modify_avatar,name='modify_avatar'),
    url(r'^login/callback\?*',views.third_login,name="callback"),
]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

comments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from types import MethodType #类动态绑定方法
import os
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import User


class Comment(models.Model):
    name = models.ForeignKey(User,related_name='user_comments',null=True,blank=True,on_delete=models.SET_NULL,default=None)
    email = models.EmailField(max_length=255,blank=True)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('Blog_Module.Article')

    def __unicode__(self):
        return self.text[:20]
    class Meta:
        ordering = ['-created_time']
        db_table = 'Comment'

AVATAR_ROOT = 'avatar'
AVATAR_DEFAULT = os.path.join(AVATAR_ROOT, 'Logo.jpeg')


class User_Avatar(models.Model):
    """user avatar"""
    user = models.ForeignKey(User)
    avatar = models.ImageField(upload_to=AVATAR_ROOT)


# 动态绑定头像相关的方法
def get_avatar_url(self):
    try:
        avatar = User_Avatar.objects.filter(user=self.id)
        avatar = avatar[len(avatar)-1]
        return avatar.avatar
    except Exception as e:
        return AVATAR_DEFAULT


# 动态绑定方法
User.get_avatar_url = MethodType(get_avatar_url, None, User)

templates/AddValueTodb.html
<!DOCTYPE html>
<html>
<head>
	<title>add values to mysql</title>
</head>
<body>
<form action="" method="post">
	<input type="text" name="title"><br>
	<input type="" name="">	
</form>
</body>
</html>

templates/Modify_avatar.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block body %}
<h2 style="text-align: center">请上传需要修改的头像图片</h2>
    <div style="text-align: center">

        <form method="POST" enctype="multipart/form-data" action="/modify_avatar/" style="margin-top: 10%">
        {% csrf_token %}
        <label style="color: red">{{ error }}</label><br>
        <input type="file" name="img" style="position: relative;display: inline-block">
        <input type="submit" value="Upload">
        </form>
    </div>

{% endblock %}

templates/archives_category_tags.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% block title%}孙强的个人博客{% endblock %}

{% block body %}

{% if error_Message %}
    <h2 style="text-align: center;color: red;"><i class="fa fa-meh-o" aria-hidden="true"></i> Oops!{{ error_Message }}</h2>
{% endif %}
{% for article in articles_list %}

    <div id="post-392"
         class="post-392 post">

        <div class="post-aside">
            <p class="post-date ">{{ article.created_time.year }}<br/>{{ article.created_time.month }}<br/>{{ article.created_time.day }}</p>
        </div>

        <div class="post-content">

            <h2 class="entry-title"><a href="/article/{{ article.id }}/" rel="bookmark">{% ifequal article.property 'o' %}<span style='color:red'>[原创] </span>{% else %}<span style='color:red'>[转载] </span>{% endifequal %}{{ article.title }}</a></h2>

            <div class="post-meta">
                <p>
                    <span class="date_publish"><i class="fa fa-user"></i> {{ article.author }}</span>

                    <span class="categories"><i class="fa fa-eye"></i> <a href="#">{{ article.views }} views</a></span>
                    <span class="categories">Category: <a href="#">{{ article.category }}</a></span>
                    <span class="tags"><i class="fa fa-tags"></i>Tags: {%for tag in article.tags.all%}<a href="/tag/{{tag}}">{{ tag}}</a>{%if not forloop.last%},{%endif%}{%endfor%}</span>

                    <span class="comments"><i class="fa fa-pencil-alt"></i> <a href="/article/{{ article.id }}/#comments" rel="comments">{{ article.comment_set.count }} Comments</a></span>
                    <span class="comments"><i class="fa fa-heart"></i> <a href="#" title="0">{{ article.likes }} like</a></span>
                    <span class="edit"><i class="fa fa-edit"></i> <a href="/admin/Blog_Module/article/{{ article.id }}/change/" title="{{ article.title }}">Edit</a></span>

                </p>
            </div><!-- .post-meta -->

            <div class="postBody">
                <p>
                <p>{{ article.body |truncatechars:200 }}<i style="float: right"><a href="/article/{{ article.id }}/">阅读全文...</a></i></p>
                    <p><img src="{{ article.imgurl }}" alt="" /></p>

                </p>
            </div>
        </div><!-- .post-content -->

    </div> <!-- .post -->
{% endfor %}
          {% if is_paginated %}
				<ul class="pager">
                    {% if page_obj.has_previous %}
					<li class="previous"><a href="?page={{ page_obj.previous_page_number }}">&larr; Previous</a></li>
                    {% endif %}
                    <li class="current">Page {{ page_obj.number }} of {{ paginator.num_pages }}</li>
                    {% if page_obj.has_next %}
					<li class="next"><a href="?page={{ page_obj.next_page_number }}">Next &rarr;</a></li>
                    {% endif %}
				</ul>
                {% endif %}
{%endblock%}

templates/article_detail.html
{% extends "base.html" %}
{% load static %}
{% block title%}{{detail.title}}{% endblock %}

{% block body %}

<div id="article">

  <div id="post-{{detail.id}}" class="post-{{detail.id}} post p1">
    
        <div>

            <h2 class="entry-title" style="text-align:center;"><a href="/article/{{ detail.id }}/" rel="bookmark">{% ifequal detail.property 'o' %}<span style='color:red'>[原创] </span>{% else %}<span style='color:red'>[转载] </span>{% endifequal %}{{ detail.title }}</a></h2>

            <div class="post-meta" style="margin-left:10%;">
                <p>
                    <span class="date_publish"><i class="fa fa-user"></i> {{ detail.author }}</span>
		    <span class="categories"><i class="fa fa-clock-o"></i>{{detail.created_time}}</span>
                    <span class="categories"><i class="fa fa-eye"></i> <a href="#">{{ detail.views }} views</a></span>
                    <span class="categories">Category: <a href="#">{{ detail.category }}</a></span>
                    <span class="tags"><i class="fa fa-tags"></i>Tags: {% for tag in detail.tags.all %}<a href="/tag/{{tag}}">{{tag}}</a>{% if not forloop.last %},{%endif%}{%endfor%}</span>

                    <span class="comments"><i class="fa fa-pencil-alt"></i> <a href="/article/{{ detail.id }}/#comments" rel="comments">{{ detail.comment_set.count }} Comments</a></span>
                    <span class="comments"><i class="fa fa-heart"></i> <a href="#" title="0">{{ detail.likes }} like</a></span>
                    <span class="edit"><i class="fa fa-edit"></i> <a href="/admin/Blog_Module/article/{{ detail.id }}/change/" title="{{ detail.title }}">Edit</a></span>

                </p>
            </div><!-- .post-meta -->

            <div class="postBody">
                <p>
                    <p>{{ detail.body|safe }}</p>

                </p>
            </div>
        </div><!-- .post-content -->

    </div> <!-- .post -->

<marquee direction=left behavior=scroll loop=-1 scrollamount=10 scrolldelay=10 align=top height=100 width=100% size="5" hspace=20 vspace=10 onmouseover=this.stop() onmouseout=this.start()><h1><strong>著作权归作者所有，欢迎转载，请务必注明出处！</strong></h1></marquee>
</div>

<br>
<div>
    <a href="/article/{{ pre_detail.id }}/" id="previousArticle"><label><<</label> 上一篇 {{ pre_detail.title }}</a>
    <a href="/article/{{ nex_detail.id}}/" style="float: right" id="nextArticle">下一篇 {{ nex_detail.title }}<label>>></label></a>
</div>
<br><br>

<!--悬浮导航
<div id="fudong" style="border:1px solid #454545; width:200px; height:400px; position: absolute; left: 0; top: 100px;">
{{toc|safe}}
</div>
-->


<h3><i class="fa fa-list"></i> Comment List</h3><br><br><br><br>

                            <ul class="row comment-list list-unstyled" id="comments" style="box-shadow:1px 1px 2px #A7A8AD;background:#fff;border-radius:5px;" >
                            {% for comment in comment_list %}

                <div>
                <div>
	
                    <img src="/upload/{{ comment.name.get_avatar_url}}" style="float:left;width: 60px;height: 60px;border-radius:30px;" id="avatar">
                </div>
                    <div style="margin-left: 10%">
                    <span class="nickname" id="{{comment.id}}">{{ comment.name }}</span>
                    <span class="fa fa-clock-o"></span>&nbsp;<time class="submit-date">{{ comment.created_time }}</time>
                    <a href="javascript:void(0);" onclick="return ReplyComment({{comment.id}})" style="color:red">[Reply]</a>
                    <li class="content-item" id="comment_text_{{ comment.id }}" style="margin-left: 10px">
                        {{ comment.text }}
                    </li>
                    </div>
				</div>

<hr>
                            {% empty %}
                                暂无评论
                                <hr>
                            {% endfor %}
                            </ul>

                                 <h3><i class="fa fa-comments"></i> Comments</h3><br><br><br><br>
{% if request.user.is_authenticated %}
    {% if request.user.is_active %}
                    <form action="/comment/post/{{detail.pk}}/" method="post" class="comment-form" >
                          {% csrf_token %}
                          <div class="row well">

                            <div class="col-md-20">
                              <label for="{{ form.name.id_for_label }}">昵称：</label>
                              {{ request.user.username }}&nbsp;&nbsp;<span id="user_part" style="position: absolute"></span>
                              {{ form.name.errors }}
                            </div>

                            <div class="col-md-20">
                              <label for="{{ form.text.id_for_label }}">评论内容：</label><br>
                              {{ form.text }}
                              {{ form.text.errors }}
                              <br><button type="submit" class="comment-btn" style="float: inherit">发表评论</button>
                            </div>
                          </div>
                    </form>
{% else %}
<h4 style="text-align: center" id="for_mobile">你还没有激活,请查看邮件并激活账号！</h4>
{% endif %}
{% else %}
<h4 style="text-align: center" id="for_mobile">你还没有登录，登陆后才可以发表评论！！<a href="#" data-toggle="modal" data-target="#LoginModal">登录</a>or <a href="#" data-toggle="modal" data-target="#RegModal">注册</a</h4>
{% endif %}
<!--

<div id="uyan_frame"></div>
<script type="text/javascript" src="http://v2.uyan.cc/code/uyan.js?uid=2160970"></script>
-->
    <script>
        //document.getElementById('wrap').style.display='none';
        var lastArticleID = {{ Last_id }};
        var currentId = {{ detail.id }};
        if (lastArticleID == currentId){
            document.getElementById('nextArticle').style.display='none';
        }if (currentId == 1){
            document.getElementById('previousArticle').style.display='none';
        }

    </script>

 <script>

        function ReplyComment(n) {
            var i = $('#'+n).text();
            var t = $.trim($('#comment_text_'+n).text());
            
            return $(".emojionearea-editor").focus(),$(".emojionearea-editor").html("@"+i+'<br/>'+'[quote]'+t+'[/quote]'+$(".emojionearea-editor").html()+'<br/>');
        }
    $(document).ready(function () {
        var str;
        $("#comments li").each(function () {
            str = $(this).html();

            str =str.replace(/\[quote]/g,"<fieldset style=\'border: 0px solid silver;background:#f4f0eb;color:#000;\'>");
            str =str.replace(/\[\/quote]/g,"</fieldset>");

            $(this).html(str)


        });
	$("#avatar").removeAttr('onclick');
    $("#comments #avatar").each(function(){
        if ($(this).attr('src').indexOf("/upload/http")==0){
            var url = $(this).attr('src').substring(8);
            $(this).attr('src',url);
        }
        
    });
    });

/*悬浮导航
    $(function() {
  var timer, scrollTop, sideDiv = $('#fudong').appendTo('body');
  $(window).scroll(function() {
    timer && clearTimeout(timer);
    scrollTop = $(this).scrollTop();
    timer = setTimeout(function() {
      sideDiv.animate({
        top: scrollTop + 100 + 'px'
      }, 600);
    }, 200);
  });
});
*/
</script>
{% endblock %}

templates/base_old.html
<!DOCTYPE html>
<html>
{% load static %}
{% load blog_tags %}
{% load admin_urls %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Blog{% endblock %}</title>

    <!-- Bootstrap core CSS -->
<!--
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="application/javascript" charset="utf-8"></script>
    <script src="http://cdn.gbtags.com/jquery/2.1.1/jquery.min.js" type="text/javascript" charset="utf-8"></script>
-->
	<link rel="stylesheet" href="{% static 'header.css' %}" type="text/css" media="all" />
    <link rel="stylesheet" type="text/css" href="http://apps.bdimg.com/libs/bootstrap/3.3.4/css/bootstrap.min.css"/>
    <script src="{% static 'jquery-2.0.3.min.js'%}" type="text/javascript"></script>
    <script src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js" type="text/javascript" charset="utf-8"></script>
    <link rel="stylesheet" href="{% static 'ballon.min.css'%}" />
    <link rel="stylesheet" href="{% static 'code.css'%}" />
      <link rel="stylesheet" href="{% static 'wrap.css'%}" />

    <script src="{% static 'jquery.min.js'%}" type="text/javascript"></script>

<link rel="bookmark" type="image/x-icon" href="{% static 'image/favicon.ico' %}"/>
<link rel="shortcut icon" href="{% static 'image/favicon.ico' %}">
<link rel="icon" href="{% static 'image/favicon.ico' %}">
    <script src="{% static 'jquery.mousewheel.pack.js'%}" type="text/javascript"></script>
    <script src="{% static 'jquery.easing-1.3.pack.js'%}" type="text/javascript"></script>
    <link rel="stylesheet" href="{%static 'fancybox.css'%}" />
    <script src="{% static 'fancybox.pack.js'%}" type="text/javascript"></script>
<style type="text/css">
    .post-date {
    background: #6B5D38;
    color: #fff;
    font-size: 18px;
    font-weight: bold;
    line-height: 18px;
    text-align: center;
    width: 60px;
    height: 60px;
    padding-top: 12px;
    margin: 0;
    -moz-border-radius: 30px;
    -webkit-border-radius: 30px;
    border-radius: 30px;
    }

    .active1 {
        background-color: #4CAF50;
    }
    .scrollTop{
	width:120px;
	height:130px;
	padding:5px;
	text-align:center;
	background: whiteSmoke;
	font-weight: bold;
	color: #444;
	text-decoration: none;
	position:fixed;
	top:85%;
	right:2%;
    z-index: 1000;
	display:none;
	background: url('{% static 'image/Arrow-Up.jpeg'%}') no-repeat;
    }
.scrollTop:hover{
	text-decoration:none;
}

</style>
    </head>

  <body style="background-color: #f5f5f5">


    <header id="header" class="logo-left headerPM menuPosition" role="banner" style="top: 0;">
		<div class="wf-wrap">
			<div class="wf-table">

<div id="branding" class="wf-td bit-logo-bar" style="" >
	<a  class="bitem logo nomarl" style="display: table-cell;" href="/"><span class="logospan"><img class="preload-me" src="{% static 'image/Logo.png' %}" width="228" height="141"   alt="Logo"  /></span></a>
		<div class="bitem text" style="display: table-cell;vertical-align: middle;" ><a href='/'  style='text-decoration: none;' ><div id='bit-logoText'  data-margin-left=17  style='position:relative;font-size:16px;  margin-left:17px;'><div class='logotext_outner'><div class='logotext_inner'><div><span style="font-size:20px;"><span style="color: rgb(51, 51, 51);"><strong>孙强的个人博客</strong></span></span></div>

<div>
    <span style="font-size:14px;">
    <span style="color: rgb(51, 51, 51);">
    <font face="arial, helvetica, sans-serif">
<b>SunQiang's BLOG</b>
</font>
    </span></span>
</div>
</div>
        </div>
        </div>
        </a>
        </div>

</div>


	
		<nav id="navigation" class="wf-td">
			<ul id="main-nav" class="mainmenu bit-menu-default underline-hover position-text-right">
                <li class=" menu-item menu-item-type-post_type menu-item-object-page bit-menu-post-id-7471 menu-item-7505 level-arrows-on"><form method="get" action="{% url 'Blog:search' %}"><input class="search" type="text" name="q" placeholder="search..." size="30" style="border-radius: 7px;"></form></li>
                <li id="t"><a href="/" style="font-size: 1.5em;">首页</a></li>
                <li id="t"><a href="/love/" style="font-size: 1.5em;">爱情</a></li>
                <li id="t"><a href="/resume/" style="font-size: 1.5em;">简历</a></li>
                <li id="t"><a href="/about/" style="font-size: 1.5em;font-family: Tahoma;">关于我</a></li>
</ul>

					</nav>
		<div style="display:none;" id="main-nav-slide">
									<div class="main-nav-slide-inner" data-class="" >
				<div  class="floatmenu-bar-right bit_widget_more" bitdatamarker="bitHeader-3" bitdataaction="site_fix_container" bitdatacolor="white">
					 				</div>
			</div>
		</div>


			</div>
		</div>

	</header>

	<div class="container" style="margin-left:10%;margin-right:10%;">
		<div class="row">
			<div class="col-md-8">
      {% block body %}{% endblock %}
			</div>
			<div class="col-md-4">

				<div class="well text-center" id="person" style="background-color: #fff;">
	                    <canvas id="clock" width="150px" height="150px" style="margin:0 auto;line-height:150px;"></canvas>
               <!-- <img src="{% static 'image/headshot.jpg' %}" style="width: 100px;height: 100px"><br> -->
                    
            <div class="catch-me">
            <div style="margin-top: 5px;">
            <a data-balloon="QQ" data-balloon-pos="up" target="_blank" style="margin-left: 5px;margin-right: 5px;" href='http://wpa.qq.com/msgrd?v=3&amp;uin=530631372&amp;site=qq&amp;menu=yes' class="external" rel="nofollow"><i class="fa fa-qq" style="font-size: 20px;"></i></a>
            <a data-balloon="微信" data-balloon-pos="up" target="_blank" style="margin-left: 5px;margin-right: 5px;" href="{% static 'image/weixin.jpg' %}" class="group" rel="group1"><i class="fa fa-wechat" style="font-size:20px;"></i></a>
            <a data-balloon="GitHub" data-balloon-pos="up" target="_blank" style="margin-left: 5px;margin-right: 5px;" href="https://github.com/sunqiang25/" class="external" rel="nofollow"><i class="fa fa-github" style="font-size: 22px;"></i></a>
            <!--
            <a data-balloon="知乎" data-balloon-pos="up" target="_blank" style="margin-left: 5px;margin-right: 5px;" href="https://www.zhihu.com/people/yi-yu-67" class="external" rel="nofollow"><i class="fa" style="font-size: 20px; font-weight: 500;">知</i></a>
            -->
            <a data-balloon="Email" data-balloon-pos="up" target="_blank" style="margin-left: 5px;margin-right: 5px;" href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&amp;email=530631372@qq.com" class="external" rel="nofollow"><i class="fa fa-envelope-o" style="font-size: 20px;"></i></a>
            </div>
        </div>
		        <!--<button class="btn btn-primary btn-lg">Subscribe to my feed</button>-->
				</div>

				<!-- Latest Posts -->
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4>最新文章</h4>
                        {% get_recent_articles as rencent_article_list %}
					</div>

					<ul class="list-group">
                        {% for article in rencent_article_list %}
						<li class="list-group-item"><a href="/article/{{ article.id }}/">{{ article.title}}</a></li>
					</ul>
                        {% empty %}
                    没有文章
                    {% endfor %}
				</div>
            <!--Archives-->
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4><span class="fa fa-archive"></span> 文章档案</h4>
					</div>
                    {% archives as archives_list %}
					<ul class="list-group">
                        {% for archive in archives_list %}
                            <li class="list-group-item"><a href="/archive/{{ archive.year}}/{{ archive.month}}/{{ archive.day}}/">{{ archive.year}}年{{ archive.month}}月{{ archive.day}}日</a></li>
                        {% empty %}
                        No Arctives
                        {% endfor %}
					</ul>
				</div>
				<!-- Categories -->
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4><span class="fa fa-list"></span> 文章分类</h4>
					</div>
                    {% get_categories as categories_list %}
					<ul class="list-group">
                        {% for category in categories_list %}
						<li class="list-group-item"><a href="/category/{{ category.id}}/">{{ category.name }}({{ category.num_posts }})</a></li>
                        {% empty %}
                        No Category
                        {% endfor %}
					</ul>
				</div>
				<!-- Tags -->
				<div class="panel panel-default">
                    <div class="panel-heading" style="white-space: nowrap;">
                        <h4><span class="glyphicon glyphicon-tags"></span> 文章标签</h4>
					</div>
                    {% get_tags as get_tag_list %}
					<div class="panel-body">
                        <ul class="list-inline">
                      {% for tag in get_tag_list %}

							<li><a href="/tag/{{tag.id}}/">#{{ tag.name }}</a></li>

                        {% empty %}
                            No Tags
                        {% endfor %}
                        </ul>
					</div>
				</div>

				<!-- Recent Comments -->
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4><span class="fa fa-comments"></span>最新评论</h4>
					</div>
                    {% get_comments as comment_list %}
					<ul class="list-group">
                        {% for comment in comment_list %}
						<li class="list-group-item"><a href="/article/{{comment.post_id}}/#comments">{{ comment.text}} - <em>{{ comment.name}}</em></a></li>
                        {% empty %}
                        No Comments
                        {% endfor %}
					</ul>
				</div>

			</div>
		</div>
	</div>
      <br>
<span href="#" class="scrollTop"></span>
	<!-- Footer -->
	<footer>
		<div class="container">
			<hr />
			<p class="text-center">Copyright &copy; SunQiang 2018. All rights reserved.</p>
		</div>
	</footer>
<!--wrap js file-->

    <script src="{% static 'fancybox.js'%}" type="text/javascript"></script>

<script src="{% static 'wrap.js'%}"></script>

<!--打赏 Start-->
<!--
<script>
    window.tctipConfig = {
            staticPrefix: "http://static.tctip.com",
            buttonImageId: 3,
            buttonTip:    "dashang",
            list:{
                alipay: { qrimg: "http://images.cnblogs.com/cnblogs_com/jiangqiuju/1133447/o_Ali.jpg"},
                weixin: { qrimg: "http://images.cnblogs.com/cnblogs_com/jiangqiuju/1133447/o_wx.png"},
            }
        };
</script>

<script src="{% static 'dashang.min.js'%}" />
-->
<!--打赏 End-->
<script src="{% static 'js/clock.min.js' %}"></script>
    <script>
            $(function() {
            $("#clock").drawClock();})
    </script>
<script type="text/javascript">
    $(document).ready(function(){
        $("#main-nav").find("li").each(function(){
            var a = $(this).find("a:first")[0];
            if ($(a).attr("href") === location.pathname) {
                $(this).addClass("active1");
            }else{
                $(this).removeClass("active1");
            }
        });

	$(window).scroll(function(){
		if ($(this).scrollTop() > 200) {
			$('.scrollTop').fadeIn();
		} else {
			$('.scrollTop').fadeOut();
		}
	});
	//Click event to scroll to top
	$('.scrollTop').click(function(){
		$('html,body').animate({ scrollTop: 0 }, 800);
		return false;
	});

});
</script>

  </body>
</html>

templates/login.html
<!DOCTYPE html>
{% load admin_urls %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

<form action="{% url 'account:login' %}" method="post" accept-charset="utf-8" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="username" id="username" placeholder="Please input your name...">
    <input type="password" name="password" id="password" placeholder="Please input your password" value="">
    <input type="email" name="email" id="email" placeholder="Please input your email">
    <input type="submit" value="Login">
</form>

</body>
</html>

templates/test_Message.html
{% extends "base.html" %}

{% block title %}Sunqiang的博客{% endblock %}

{% block body %}
    {#显示消息的页面#}
    <div >
        <h2 style="line-height:300%;text-align: center">{{message|safe}}</h2>

    </div>



    <script type="text/javascript">
        {#页面调整控制#}
        {% if goto_page %}
            $(function(){
                window.setTimeout(function(){
                    window.location = '{{goto_url}}';
                },5000);
            });
        {% endif %}
    </script>
{% endblock %}

templates/upload.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block body %}

<form method="POST" enctype="multipart/form-data" action="/upload/" style="margin-top: 10%">
{% csrf_token %}
<input type="file" name="img" style="position: relative;display: inline-block">
<input type="submit" value="Upload">

</form>





{% endblock %}